[package]
name = "rust_lattice_analysis"
version = "0.1.0"
edition = "2024"

[dependencies]
evalexpr = "12.0.2"
itertools = "0.14.0"
ndarray = "0.16.1"
winnow = "0.7.11"

[profile.release]
debug = "line-tables-only"

